name = "stationery-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[build]
command = "npm run build"

# Handle client-side routing for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
